### PR TITLE
link to other models

### PR DESCRIPTION
**Pull request by LippkauFelix**
added links to other models. Firstly I added the gernal approach of linkage and secondly I added the Macro model as discussed in the last Issue. Feel free to change phrases etc.

### CODE REVIEW

**Comment by olejandro** [comment]
Thanks @LippkauFelix! @antti-l do you have any comments?

**Comment by Antti-L** [comment]
> @Antti-L do you have any comments?

Well yes, because there are Macro modules also fully integrated into ETSAP-TIMES, it would be nice to make clear whether **TSAM** makes use of TIMES-Macro, or if it is using a different Macro implementation (I vaguely recall having heard of some IER implementation).  If it is a different implementation, it would also be good to know what are the advantages of that Macro implementation in comparison, and if it is proprietary (owned by IER?) or openly available (and if so, where).  Based on the description, it does sound very much similar to the Macro integrated in TIMES, but I am left uncertain about whether the ETSAP Macro code is actually being referred to here or not.

**Comment by olejandro** [comment]
Thanks for looking into this @LippkauFelix

**Comment by DeepakIERStuttgart** [comment]
Please add me as assignee

**Review by DeepakIERStuttgart — APPROVED** [review]

**Review by DeepakIERStuttgart — APPROVED** [review]

**Comment by olejandro** [comment]
> I talked to Markus and can answer you the question now. TSAM is fully built on TIAM-Macro, but it uses adjusted parameters. So actually there is only TIAM-Macro. I will change the text and refer to TIAM macro.

@DeepakIERStuttgart I can see you've approved this, but the changes that @LippkauFelix mentioned are still missing.

**Pull request closed without merging**
